import {
  Apple,
  Armchair,
  Backpack,
  Bed,
  Bike,
  Bird,
  BookOpen,
  Box,
  Briefcase,
  Bus,
  Cake,
  Car,
  Cat,
  Clock,
  Coffee,
  Dog,
  Flower2,
  Keyboard,
  Laptop,
  Luggage,
  Microwave,
  Milk,
  Monitor,
  Mouse,
  Pizza,
  Plane,
  Refrigerator,
  Scissors,
  Ship,
  Shirt,
  Smartphone,
  Sofa,
  Sprout,
  TrafficCone,
  TrainFront,
  Truck,
  Tv,
  Umbrella,
  Utensils,
  Wine,
  type LucideIcon,
} from "lucide-react";

import { classKey } from "@/utils/format";

/** Biểu tượng theo lớp COCO (tên so không phân biệt hoa / thường); lớp chưa có biểu tượng riêng dùng hình hộp */
const ICONS: Record<string, LucideIcon> = {
  laptop: Laptop,
  mouse: Mouse,
  keyboard: Keyboard,
  "cell phone": Smartphone,
  tv: Monitor,
  remote: Tv,
  book: BookOpen,
  clock: Clock,
  vase: Flower2,
  scissors: Scissors,
  bottle: Milk,
  "wine glass": Wine,
  cup: Coffee,
  fork: Utensils,
  knife: Utensils,
  spoon: Utensils,
  bowl: Utensils,
  chair: Armchair,
  couch: Sofa,
  bed: Bed,
  "potted plant": Sprout,
  microwave: Microwave,
  refrigerator: Refrigerator,
  backpack: Backpack,
  umbrella: Umbrella,
  handbag: Briefcase,
  suitcase: Luggage,
  tie: Shirt,
  apple: Apple,
  pizza: Pizza,
  cake: Cake,
  donut: Cake,
  car: Car,
  bicycle: Bike,
  motorcycle: Bike,
  bus: Bus,
  truck: Truck,
  train: TrainFront,
  airplane: Plane,
  boat: Ship,
  "traffic light": TrafficCone,
  cat: Cat,
  dog: Dog,
  bird: Bird,
};

interface Props {
  name: string | null | undefined;
  size?: number;
  strokeWidth?: number;
}

export const ObjectIcon = ({ name, size = 18, strokeWidth = 1.7 }: Props) => {
  const Icon = (name && ICONS[classKey(name)]) || Box;
  return <Icon size={size} strokeWidth={strokeWidth} aria-hidden />;
};
